@ECHO OFF

IF "%1"=="" (
    SET TEMP_UNITY_DEV_PATH=c:\code\unity.1
) ELSE (
    SET TEMP_UNITY_DEV_PATH=c:\code\unity.%1
)

IF NOT EXIST %TEMP_UNITY_DEV_PATH% (
    ECHO %TEMP_UNITY_DEV_PATH% doesn't exist. 2>&1
    SET UNITY_DEV_PATH=
    GOTO :CLEANUP
)

SET UNITY_DEV_PATH=%TEMP_UNITY_DEV_PATH%
CD %UNITY_DEV_PATH%

CALL ugetbranch

:CLEANUP
SET TEMP_UNITY_DEV_PATH=
