@ECHO OFF

IF "%1"=="" (
    SET TEMP_VISSCRIPT_DEV_PATH=c:\code\com.unity.visualscripting.1
) ELSE (
    SET TEMP_VISSCRIPT_DEV_PATH=c:\code\com.unity.visualscripting.%1
)

IF NOT EXIST %TEMP_VISSCRIPT_DEV_PATH% (
    ECHO %TEMP_VISSCRIPT_DEV_PATH% doesn't exist. 2>&1
    SET VISSCRIPT_DEV_PATH=
    GOTO :CLEANUP
)

SET VISSCRIPT_DEV_PATH=%TEMP_VISSCRIPT_DEV_PATH%
CD %VISSCRIPT_DEV_PATH%

CALL vsgetbranch

:CLEANUP
SET TEMP_VISSCRIPT_DEV_PATH=
