@ECHO OFF

SET TEMPFILENAME=%TEMP%\broutput.txt

hg branch > %TEMPFILENAME% 2> nul
IF %ERRORLEVEL% NEQ 0 (
    GOTO :CLEANUP
)

SET TEMP_UNITY_BRANCH_NAME=
FOR /F %%I IN (%TEMPFILENAME%) DO SET TEMP_UNITY_BRANCH_NAME=%%I

SET UNITY_BRANCH_NAME=%TEMP_UNITY_BRANCH_NAME%
ECHO Current [94mUnity[0m branch is [91m%UNITY_BRANCH_NAME%[0m

SET UNITY_DISPLAY_BRANCH_NAME=%UNITY_BRANCH_NAME%
IF /i "%UNITY_BRANCH_NAME:~0,12%"=="editor/tech/" SET UNITY_DISPLAY_BRANCH_NAME=%UNITY_BRANCH_NAME:editor/tech/=E/T/%
IF /i "%UNITY_BRANCH_NAME:~0,23%"=="editor/visualscripting/" SET UNITY_DISPLAY_BRANCH_NAME=%UNITY_BRANCH_NAME:editor/visualscripting/=E/VS/%

TITLE %UNITY_DISPLAY_BRANCH_NAME%

:CLEANUP
IF EXIST %TEMPFILENAME% (
    DEL %TEMPFILENAME%
)
SET TEMP_UNITY_BRANCH_NAME=
SET TEMPFILENAME=
